name: built_path
version: 0.1.0
description: >-
  Process SVG Path data into Flutter Path objects
  using build_runner.
homepage: https://github.com/dnfield/flutter_built_path
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  # flutter: ">=0.5.1 <2.0.0"
    
dependencies:
  analyzer: ^2.3.0
  build: ^2.1.0
  #built_path_annotations: ^0.1.0
  path_parsing: ^0.2.1
  source_gen: ^1.1.1
  # flutter:
  #   sdk: flutter

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.1.2
  build_test: ^2.1.3
  test: ^1.18.0
